name: "My Python Commit Check"
description: "Checks commit messages using a Python script"

inputs:
  github_token:
    required: true
    description: "GitHub token"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r "${{ github.action_path }}/requirements.txt"
      shell: bash

    - name: Export GitHub token to environment
      run: echo "INPUT_GITHUB_TOKEN=${{ inputs.github_token }}" >> $GITHUB_ENV
      shell: bash

    - name: Run commit check
      run: python "${{ github.action_path }}/check_commits.py"
      shell: bash
