name: "My Python Commit Check"
description: "Checks commit messages using a Python script"

inputs:
  repo:
    required: true
    description: "Repository name in owner/repo format"

  pr_number:
    required: true
    description: "Pull request number"

  desc-char-limit:
    required: false
    default: "72"
    description: "Character limit for description"

  sub-char-limit:
    required: false
    default: "50"
    description: "Character limit for subject"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('${{ github.action_path }}/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      shell: bash
      run: pip install -r ${{ github.action_path }}/requirements.txt

    - name: Check commit messages
      shell: bash
      run: |
        python ${{ github.action_path }}/check_commits.py \
          --token "${{ secrets.GITHUB_TOKEN }}" \
          --repo "${{ inputs.repo }}" \
          --pr-number "${{ inputs.pr_number }}" \
          --desc-limit "${{ inputs.desc-char-limit }}" \
          --sub-limit "${{ inputs.sub-char-limit }}"
