name: "My Python Commit Check"
description: "Checks commit messages using a Python script"

inputs:
  github_token:
    required: true
    description: "GitHub token"

  desc-char-limit:
    required: false
    default: "72"
    description: "Character limit for description"
    
  sub-char-limit:
    required: false
    default: "50"
    description: "Character limit for subject"


runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('${{ github.action_path }}/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      shell: bash
      run: pip install -r ${{ github.action_path }}/requirements.txt
      
   - name: Extract PR number
     run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
     shell: bash

   - name: Upload artifacts
     shell: bash
     run: |
      python ${{ github.action_path }}/check_commits.py \
        --token "${{ inputs.github_token }}" \
        --description-character-limit "${{ inputs.desc-char-limit }}" \
        --subject-character-limit "${{ inputs.sub-char-limit }}"
