name: "My Python Commit Check"
description: "Checks commit messages using a Python script"

inputs:
  github_token:
    required: true
    description: "GitHub token"

  message:
    required: false
    default: "true"
    description: "Check commit message format"

  branch:
    required: false
    default: "true"
    description: "Check branch name"

  author-name:
    required: false
    default: "true"
    description: "Check author name"

  author-email:
    required: false
    default: "true"
    description: "Check author email"

  commit-signoff:
    required: false
    default: "true"
    description: "Check if commit is signed off"

  merge-base:
    required: false
    default: "true"
    description: "Check merge base"

  imperative:
    required: false
    default: "true"
    description: "Check if message is in imperative mood"

  job-summary:
    required: false
    default: "true"
    description: "Include summary in job output"

  char-limit:
    required: false
    default: "72"
    description: "Character limit for subject and description"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r "${{ github.action_path }}/requirements.txt"
      shell: bash

    - name: Export inputs to environment
      run: |
        echo "INPUT_GITHUB_TOKEN=${{ inputs.github_token }}" >> $GITHUB_ENV
        echo "INPUT_MESSAGE=${{ inputs.message }}" >> $GITHUB_ENV
        echo "INPUT_BRANCH=${{ inputs.branch }}" >> $GITHUB_ENV
        echo "INPUT_AUTHOR_NAME=${{ inputs['author-name'] }}" >> $GITHUB_ENV
        echo "INPUT_AUTHOR_EMAIL=${{ inputs['author-email'] }}" >> $GITHUB_ENV
        echo "INPUT_COMMIT_SIGNOFF=${{ inputs['commit-signoff'] }}" >> $GITHUB_ENV
        echo "INPUT_MERGE_BASE=${{ inputs['merge-base'] }}" >> $GITHUB_ENV
        echo "INPUT_IMPERATIVE=${{ inputs.imperative }}" >> $GITHUB_ENV
        echo "INPUT_JOB_SUMMARY=${{ inputs['job-summary'] }}" >> $GITHUB_ENV
        echo "INPUT_CHAR_LIMIT=${{ inputs['char-limit'] }}" >> $GITHUB_ENV
      shell: bash

    - name: Debug inputs
      run: |
        echo "INPUT_COMMIT_SIGNOFF=$INPUT_COMMIT_SIGNOFF"
        echo "INPUT_IMPERATIVE=$INPUT_IMPERATIVE"
      shell: bash

    - name: Extract PR number
      run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
      shell: bash

    - name: Run commit check
      run: python "${{ github.action_path }}/check_commits.py"
      shell: bash
